name: Continuous Deployment via SSH
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  # Uncomment the following lines to enable automatic deployment on push to the main branch
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        env:
          DEPLOYUSERSSHKEY: ${{ secrets.DEPLOYUSERSSHKEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOYUSERSSHKEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH Key to SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Execute Deployment Commands
        run: |
          ssh -o StrictHostKeyChecking=no deployuser@44.238.195.106 << 'EOF'
            set -e # Exit immediately if a command exits with a non-zero status
            source ~/.profile || true
            source ~/.bashrc || true
            cd ~/belindasFrontEnd
            git pull origin main
            source ~/.nvm/nvm.sh
            # Read the Node.js version from .nvmrc
            NODE_VERSION=$(cat .nvmrc)
            nvm install $NODE_VERSION
            nvm use $NODE_VERSION
            npm install
            npm run build
            pm2 restart belindas-frontend
          EOF
